 const PageMappings = {
  "find doctors": "/find-doctors",
  "doctors": "/find-doctors",
  "diagnosis": "/symptom-checker",
  "symptom checker": "/symptom-checker",
  "reports": "/reports",
  "my appointments": "/book-appointment",
  "appointments": "/book-appointment",
  "book appointment": "/book-appointment",
  "fitness planner": "/fitness",
  "chat with assistant": "/chat",
  'chat': "/chat",
  "assistant": "/chat",
  "diet planner": "/diet-planner",
  "diet": "/diet-planner",
  "services": "/services",
  'about': "/about",
  "community": "/community",
};
export default PageMappings;