// src/components/FitnessPlanner.jsx
import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FaDumbbell, FaRunning, FaWalking, FaBiking, FaSwimmer, FaRedo } from "react-icons/fa";
import API from "../../utils/Api"; // Assuming API client is configured
import { useAuth } from "../../context/AuthContext"; // Assuming Auth Context is available
import FitnessResults from "./FitnessResults";
import FitnessHistory from "./FitnessHistory";

const weeklyGoals = [
  "3 sessions/week (Beginner)",
  "4 sessions/week (Intermediate)",
  "5 sessions/week (Advanced)",
];

const FitnessPlanner = () => {
  const { user } = useAuth();
  const userId = user?._id;

  const [height, setHeight] = useState("");
  const [weight, setWeight] = useState("");
  const [targetWeight, setTargetWeight] = useState("");
  const [weeklyGoal, setWeeklyGoal] = useState(weeklyGoals[0]);
  const [preferredExercises, setPreferredExercises] = useState(""); // 💡 NEW STATE for user preference
  
  const [bmi, setBmi] = useState(null);
  const [plan, setPlan] = useState(null); // Now stores the full structured plan object
  const [tip, setTip] = useState("");
  const [history, setHistory] = useState([]);

  // Tips are now generated by the AI on the backend, so we simplify this local array
  // const tips = [ ... ]; 

  const fetchHistory = async () => {
    try {
      if (!userId) return;
      const res = await API.get(`/fitness/history/${userId}`);
      if (res.data.success) {
        // If the plan in history is stored as a JSON string, you might need to parse it here:
        const historyData = res.data.history.map(entry => ({
            ...entry,
            plan: typeof entry.plan === 'string' ? JSON.parse(entry.plan) : entry.plan 
        }));
        setHistory(historyData);
      } else {
        setHistory([]);
      }
    } catch (err) {
      console.error("❌ Error fetching fitness history:", err);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, [userId]);

  const calculateBMI = async () => {
    if (!height || !weight) return alert("Please enter current height and weight.");
    if (targetWeight && parseFloat(targetWeight) <= 0) return alert("Target weight must be a positive number.");

    const heightInMeters = height / 100;
    const bmiValue = (weight / (heightInMeters * heightInMeters)).toFixed(1);

    let category = "";
    
    // Set BMI Category
    if (bmiValue < 18.5) category = "Underweight";
    else if (bmiValue >= 18.5 && bmiValue <= 24.9) category = "Normal";
    else if (bmiValue >= 25 && bmiValue <= 29.9) category = "Overweight";
    else category = "Obese";
    
    
    try {
      // 1. Call Backend API to generate the AI-based plan
      const planRes = await API.post("/fitness/generate", { 
          userId, 
          height, 
          weight, 
          weeklyGoal, 
          targetWeight,
          preferredExercises // 💡 SEND NEW PREFERENCE
      });

      // 2. Extract structured data from the response
      const { 
          bmi: finalBmi, 
          category: finalCategory, 
          calories, 
          plan: structuredPlan, // This is the full {warmup, main_workout, cooldown} object
          tip 
      } = planRes.data;

      // The structured plan includes all details:
      const bmiData = { 
          value: finalBmi, 
          category: finalCategory, 
          calories, 
          targetWeight: targetWeight || null, 
          weeklyGoal, 
          finalRecommendation: `Based on your goal of **${weeklyGoal}** and preference, here is your AI-generated daily plan.` 
      };
      
      setBmi(bmiData);
      setPlan(structuredPlan); // Set the entire structured plan object
      setTip(tip);

      // Re-fetch history to include the new entry
      if (userId) {
        fetchHistory();
      } else {
        console.warn("⚠️ No userId found, not saving to backend");
      }
    } catch (err) {
      console.error("❌ Error generating fitness data:", err);
      alert(`Error generating plan: ${err.response?.data?.message || err.message}`);
    }
  };

  const resetPlanner = () => {
    setHeight("");
    setWeight("");
    setTargetWeight("");
    setWeeklyGoal(weeklyGoals[0]);
    setPreferredExercises(""); // Reset new state
    setBmi(null);
    setPlan(null);
    setTip("");
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-white text-gray-800 px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="bg-white rounded-2xl shadow-2xl border border-teal-100 p-8 w-full max-w-lg"
      >
        <h1 className="text-3xl md:text-4xl font-extrabold text-center text-teal-600 mb-6">
          🏋️ AI Fitness Planner
        </h1>
        <div className="space-y-4 mb-6">
          {/* Input 1: Height */}
          <input
            type="number"
            placeholder="Enter current height (cm)"
            value={height}
            onChange={(e) => setHeight(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-gray-50 border border-gray-300 focus:ring-2 focus:ring-teal-500 focus:outline-none text-gray-800"
          />
          {/* Input 2: Current Weight */}
          <input
            type="number"
            placeholder="Enter current weight (kg)"
            value={weight}
            onChange={(e) => setWeight(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-gray-50 border border-gray-300 focus:ring-2 focus:ring-teal-500 focus:outline-none text-gray-800"
          />
          {/* Input 3: Target Weight */}
          <input
            type="number"
            placeholder="Enter target weight (kg, optional)"
            value={targetWeight}
            onChange={(e) => setTargetWeight(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-gray-50 border border-gray-300 focus:ring-2 focus:ring-teal-500 focus:outline-none text-gray-800"
          />
          {/* Input 4: Weekly Goal (DROPDOWN) */}
          <select
            value={weeklyGoal}
            onChange={(e) => setWeeklyGoal(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-gray-50 border border-gray-300 focus:ring-2 focus:ring-teal-500 focus:outline-none text-gray-800 appearance-none"
          >
            {weeklyGoals.map((goal) => (
              <option key={goal} value={goal}>
                Weekly Goal: {goal}
              </option>
            ))}
          </select>
          {/* Input 5: Preferred Exercises (NEW INPUT) */}
          <input
            type="text"
            placeholder="Preferred exercises (e.g., cycling, yoga, weights)"
            value={preferredExercises}
            onChange={(e) => setPreferredExercises(e.target.value)}
            className="w-full px-4 py-3 rounded-xl bg-gray-50 border border-gray-300 focus:ring-2 focus:ring-teal-500 focus:outline-none text-gray-800"
          />


          <div className="flex space-x-3 pt-2">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={calculateBMI}
              className="flex-1 py-3 rounded-xl font-semibold text-lg bg-teal-600 text-white shadow-md hover:bg-teal-700 transition"
            >
              Generate Plan
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={resetPlanner}
              className="p-3 rounded-xl bg-gray-200 hover:bg-gray-300 text-teal-600 shadow-md"
            >
              <FaRedo />
            </motion.button>
          </div>
        </div>
        <FitnessResults bmi={bmi} plan={plan} tip={tip} />
        <FitnessHistory history={history} fetchHistory={fetchHistory} />
      </motion.div>
    </div>
  );
};

export default FitnessPlanner;